- name: Установка EPEL-release
  yum:
    name: "{{ epel_package }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Установка Apache HTTP Server
  yum:
    name: "{{ httpd_package }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Установка Git
  yum:
    name: "{{ git_package }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Установка других необходимых пакетов
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ some_additional_packages }}"
  when: ansible_os_family == "RedHat"