---
- name: Include os specific tasks
  include_tasks: '{{ ansible_os_family | lower }}.yml'

- name: Include os specific vars
  include_vars: '{{ ansible_os_family | lower }}.yml'

- name: Add the user
  user:
    name: monicahq
    shell: /usr/bin/nologin
    home: /home/monicahq

- name: Ensure folder id exist
  file:
    path: /srv/monicahq
    state: directory
    owner: monicahq
    group: '{{ php_group }}'

- name: check out master branch
  become_user: monicahq
  git:
    repo: 'https://github.com/monicahq/monica'
    dest: /srv/monicahq
    version: main
  notify:
    - reload service php-fcgi

- name: install composer
  include_role:
    name: geerlingguy.composer

- name: install composer dependencies
  become_user: monicahq
  composer:
    command: install
    working_dir: /srv/monicahq
  notify:
    - reload service php-fcgi

- name: prepare configuration
  template:
    src: env.j2
    dest: /srv/monicahq/.env
  notify:
    - reload service php-fcgi

- name: Run an initial key generation
  command: "/usr/bin/php /srv/monicahq/artisan key:generate"
  args:
    chdir: /srv/monicahq/
  tags: molecule-notest
  notify:
    - reload service php-fcgi

- name: Run an initial migration
  command: "/usr/bin/php /srv/monicahq/artisan setup:production --force"
  args:
    chdir: /srv/monicahq/
  tags: molecule-notest

- name: Place a scheduler cron job
  cron:
    user: monicahq
    name: "scheduler"
    job: "/usr/bin/php /srv/monicahq/artisan schedule:run"

- name: Recursively change ownership of a directory
  file:
    path: /srv/monicahq
    state: directory
    recurse: yes
    owner: monicahq
    group: '{{ php_group }}'
  changed_when: false

- name: Put right permissions to storage
  file:
    path: /srv/monicahq/storage
    state: directory
    recurse: yes
    mode: g+w

- name: Create nginx vhost config
  template:
    src: monicahq.conf.j2
    dest: '{{ nginx_conf_dir }}/monica.conf'
  notify:
    - reload service nginx

- name: Remove default nginx configuration
  file:
    path: '{{ nginx_conf_dir }}/default'
    state: absent
  notify:
    - reload service nginx
