dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian11
    image: geerlingguy/docker-debian11-ansible
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: fedora36
    image: geerlingguy/docker-fedora36-ansible
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
